'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { transcriptApi } from '@/lib/api'

export default function TranscriptHistoryPage() {
  const router = useRouter()
  const [transcripts, setTranscripts] = useState<any[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    loadHistory()
  }, [])

  const loadHistory = async () => {
    try {
      setIsLoading(true)
      const response = await transcriptApi.getHistory()
      setTranscripts(response.data || [])
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to load transcript history')
    } finally {
      setIsLoading(false)
    }
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="w-12 h-12 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Transcript History</h1>
          <p className="text-gray-600 mt-1">All generated transcripts and their verification codes</p>
        </div>
        <button
          onClick={() => router.push('/transcript')}
          className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg font-semibold hover:bg-gray-50 transition-colors"
        >
          Back to Transcript
        </button>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-6 py-4 rounded-lg">{error}</div>
      )}

      {transcripts.length === 0 ? (
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-8 text-center">
          <p className="text-gray-600">No transcripts have been generated yet.</p>
          <button
            onClick={() => router.push('/transcript')}
            className="mt-4 px-4 py-2 bg-primary text-white rounded-lg font-semibold hover:bg-primary-dark transition-colors"
          >
            Go to Transcript
          </button>
        </div>
      ) : (
        <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase">Date</th>
                <th className="px-6 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Type</th>
                <th className="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase">Verification Code</th>
                <th className="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase">Generated By</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {transcripts.map((t: any) => (
                <tr key={t.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 text-sm text-gray-900">
                    {t.generatedAt ? new Date(t.generatedAt).toLocaleString() : 'N/A'}
                  </td>
                  <td className="px-6 py-4 text-center">
                    <span className={`text-xs px-3 py-1 rounded-full font-medium ${t.isOfficial ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'}`}>
                      {t.isOfficial ? 'Official' : 'Unofficial'}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    {t.hash ? (
                      <code className="text-sm font-mono bg-gray-100 px-3 py-1 rounded">{t.hash}</code>
                    ) : (
                      <span className="text-sm text-gray-400">N/A</span>
                    )}
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-600">{t.generatedByName || 'Self'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
        <p className="text-sm text-blue-900">
          <span className="font-semibold">Verification:</span> Each official transcript has a unique verification code.
          This code can be used at the university&apos;s diploma inquiry page to verify the authenticity of the document.
        </p>
      </div>
    </div>
  )
}
